version: '3'
services:
  server:
    image: rancher/k3s:v0.4.0
    command: server --disable-agent
    environment:
    - K3S_CLUSTER_SECRET=somethingtotallyrandom
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    # - K3S_KUBECONFIG_MODE=666
    volumes:
    - k3s-server:/var/lib/rancher/k3s
    # This is just so that we get the kubeconfig file out
    - .:/output
    ports:
    - 6443:6443

  node1:
    image: rancher/k3s:v0.4.0
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_URL=https://server:6443
    - K3S_CLUSTER_SECRET=somethingtotallyrandom
    # Can also use K3S_TOKEN from /var/lib/rancher/k3s/server/node-token instead of K3S_CLUSTER_SECRET
    #- K3S_TOKEN=K13849a67fc385fd3c0fa6133a8649d9e717b0258b3b09c87ffc33dae362c12d8c0::node:2e373dca319a0525745fd8b3d8120d9c
    ports:
    - 80:80

  node2:
    image: rancher/k3s
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_URL=https://server:6443
    - K3S_CLUSTER_SECRET=somethingtotallyrandom
    # Can also use K3S_TOKEN from /var/lib/rancher/k3s/server/node-token instead of K3S_CLUSTER_SECRET
    #- K3S_TOKEN=K13849a67fc385fd3c0fa6133a8649d9e717b0258b3b09c87ffc33dae362c12d8c0::node:2e373dca319a0525745fd8b3d8120d9c

  node3:
    image: rancher/k3s
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_URL=https://server:6443
    - K3S_CLUSTER_SECRET=somethingtotallyrandom

  node4:
    image: rancher/k3s
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_URL=https://server:6443
    - K3S_CLUSTER_SECRET=somethingtotallyrandom

  # node5:
  #   image: rancher/k3s
  #   tmpfs:
  #   - /run
  #   - /var/run
  #   privileged: true
  #   environment:
  #   - K3S_URL=https://server:6443
  #   - K3S_CLUSTER_SECRET=somethingtotallyrandom

  # node6:
  #   image: rancher/k3s
  #   tmpfs:
  #   - /run
  #   - /var/run
  #   privileged: true
  #   environment:
  #   - K3S_URL=https://server:6443
  #   - K3S_CLUSTER_SECRET=somethingtotallyrandom

  # node7:
  #   image: rancher/k3s
  #   tmpfs:
  #   - /run
  #   - /var/run
  #   privileged: true
  #   environment:
  #   - K3S_URL=https://server:6443
  #   - K3S_CLUSTER_SECRET=somethingtotallyrandom

  # node8:
  #   image: rancher/k3s
  #   tmpfs:
  #   - /run
  #   - /var/run
  #   privileged: true
  #   environment:
  #   - K3S_URL=https://server:6443
  #   - K3S_CLUSTER_SECRET=somethingtotallyrandom

  # node9:
  #   image: rancher/k3s
  #   tmpfs:
  #   - /run
  #   - /var/run
  #   privileged: true
  #   environment:
  #   - K3S_URL=https://server:6443
  #   - K3S_CLUSTER_SECRET=somethingtotallyrandom
    # Can also use K3S_TOKEN from /var/lib/rancher/k3s/server/node-token instead of K3S_CLUSTER_SECRET
    #- K3S_TOKEN=K13849a67fc385fd3c0fa6133a8649d9e717b0258b3b09c87ffc33dae362c12d8c0::node:2e373dca319a0525745fd8b3d8120d9c

volumes:
  k3s-server: {}